TEST_API_SECRET = "organizations/test-organization/apiKeys/test-api-key"
TEST_API_KEY = "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIKwf3Uox30cRWzRBOPoPOH5p0Gpb0Dt8zUKXUEM5fMkGoAoGCCqGSM49\nAwEHoUQDQgAEbAtpLlSZYVOwYICz+uEyxcS29vRIujiES/gQ1DC7FV4zK4JuYE9v\nqDyGZQYjdXHLM7I6f/QnnOITL+dXYWBHRA==\n-----END EC PRIVATE KEY-----\n"
